- id: check-python-dependencies
  name: Check Python Dependencies
  description: Check if all Python imports are declared in requirements.txt
  entry: python src/check_dependencies.py
  language: python
  files: \.py$
  require_serial: false
  additional_dependencies: []
  args: ['--quiet']

- id: check-python-dependencies-verbose
  name: Check Python Dependencies (Verbose)
  description: Check Python dependencies with detailed output
  entry: python src/check_dependencies.py
  language: python
  files: \.py$
  require_serial: false
  additional_dependencies: []

- id: check-python-dependencies-fail-fast
  name: Check Python Dependencies (Fail Fast)
  description: Check dependencies and exit immediately on first missing dependency
  entry: python src/check_dependencies.py
  language: python
  files: \.py$
  require_serial: true
  additional_dependencies: []
  args: ['--quiet']