name: "PyImportSync"
description: "Synchronize Python imports with requirements.txt - ensure all imports are properly declared"
author: "trivedi-vatsal"

branding:
  icon: "package"
  color: "blue"

inputs:
  project-path:
    description: "Path to the Python project directory (relative to repository root)"
    required: false
    default: "."
  requirements-file:
    description: "Path to requirements.txt file (relative to project-path)"
    required: false
    default: "requirements.txt"
  ignore-dirs:
    description: "Comma-separated list of directories to ignore (in addition to defaults)"
    required: false
    default: ""
  fail-on-missing:
    description: "Whether to fail the action if missing dependencies are found"
    required: false
    default: "true"
  output-file:
    description: "Output file to save missing dependencies (optional)"
    required: false
    default: ""
  use-pipreqs:
    description: "Whether to use pipreqs for additional dependency detection"
    required: false
    default: "true"
  respect-gitignore:
    description: "Whether to respect .gitignore patterns when scanning files"
    required: false
    default: "true"

outputs:
  missing-dependencies:
    description: "List of missing dependencies (newline-separated)"
    value: ${{ steps.check-deps.outputs.missing-dependencies }}
  missing-count:
    description: "Number of missing dependencies found"
    value: ${{ steps.check-deps.outputs.missing-count }}
  status:
    description: "Status of the check (success, missing-deps, error)"
    value: ${{ steps.check-deps.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install UV
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: |
        uv pip install --system pipreqs==0.4.13 packaging pathspec rich

    - name: Run dependency check
      id: check-deps
      shell: bash
      working-directory: ${{ inputs.project-path }}
      run: |
        python ${{ github.action_path }}/src/check_dependencies.py \
          --project-root . \
          --requirements-file ${{ inputs.requirements-file }} \
          --ignore-dirs "${{ inputs.ignore-dirs }}" \
          --output "${{ inputs.output-file }}" \
          ${{ inputs.use-pipreqs == 'true' && '' || '--no-pipreqs' }} \
          ${{ inputs.respect-gitignore == 'true' && '' || '--no-gitignore' }} \
          ${{ inputs.fail-on-missing == 'true' && '' || '' }}
