name: Advanced Dependency Check
on:
  push:
  pull_request:

jobs:
  # Check multiple requirement files
  multi-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        requirements-file:
          - "requirements.txt"
          - "requirements-dev.txt"
          - "requirements-test.txt"

    steps:
      - uses: actions/checkout@v4
      - name: Check Dependencies - ${{ matrix.requirements-file }}
        uses: trivedi-vatsal/PyImportSync@v1
        with:
          requirements-file: ${{ matrix.requirements-file }}
          fail-on-missing: false # Don't fail on dev/test deps
          output-file: "missing-${{ matrix.requirements-file }}.txt"

  # Check specific project subdirectory
  subdirectory-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check API Dependencies
        uses: trivedi-vatsal/PyImportSync@v1
        with:
          project-path: "src/api"
          requirements-file: "requirements/api.txt"
          ignore-dirs: "tests,docs,examples"

  # Conditional check based on file changes
  conditional-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need to compare with previous commit

      - name: Check if requirements changed
        id: requirements-changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q requirements; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check Dependencies (only if requirements changed)
        if: steps.requirements-changed.outputs.changed == 'true'
        uses: trivedi-vatsal/PyImportSync@v1
        with:
          fail-on-missing: true
